### ISSUE TITLE
"mb_substr() expects parameter 3 to be integer, string given" with ja_JP

### ISSUE THREAD

**Issue by ushiyasan** [fzaninotto/Faker#1003]
```
[2016-08-24 16:39:17] local.ERROR: ErrorException: mb_substr() expects parameter 3 to be integer, string given in /home/vagrant/Code/vendor/fzaninotto/faker/src/Faker/Provider/ja_JP/Text.php:623
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mb_substr() exp...', '/home/vagrant/C...', 623, Array)
#1 /home/vagrant/Code/vendor/fzaninotto/faker/src/Faker/Provider/ja_JP/Text.php(623): mb_substr('\xE6\x9E\xB6\xE6\xA9\x8B\xE6\xBC\x94\xE7\xBF\x92\xE3\x81\x8B...', 98, 'UTF-8')
#2 /home/vagrant/Code/vendor/fzaninotto/faker/src/Faker/Provider/Text.php(75): Faker\Provider\ja_JP\Text::appendEnd('\xE6\x9E\xB6\xE6\xA9\x8B\xE6\xBC\x94\xE7\xBF\x92\xE3\x81\x8B...')
#3 [internal function]: Faker\Provider\Text->realText(100)
#4 /home/vagrant/Code/vendor/fzaninotto/faker/src/Faker/Generator.php(196): call_user_func_array(Array, Array)
```

I think

``$last = mb_substr($text, mb_strlen($text)-1, 'UTF-8');``

must be

``$last = mb_substr($text, mb_strlen($text)-1, null, 'UTF-8'); ``

**Comment by adriantombu** [comment]
Looks like it's already the case in the current version, maybe your version is outdated :)

https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/ja_JP/Text.php#L623

**Comment by adiachenko** [comment]
@fzaninotto Just kindly notifying you that the issue persists in v1.6.0. Below is reproducible example: 

```
C:\app\pulpfi [ln_create +5 ~5 -0 !]> composer show -D
barryvdh/laravel-ide-helper v2.2.3 Laravel IDE Helper, generates correct PHPDocs for all Facade classes, to improve auto-completion.
fzaninotto/faker            v1.6.0 Faker is a PHP library that generates fake data for you.
laravel/framework           v5.4.6 The Laravel Framework.
laravel/tinker              v1.0.0 Powerful REPL for the Laravel framework.
mockery/mockery             0.9.7  Mockery is a simple yet flexible PHP mock object framework for use in unit testing with PHPUnit, PHPSpec or any other testing framework. Its core goal is to offer a test double framework with a succinct API capable of clearly d...
phpunit/phpunit             5.7.9  The PHP Unit Testing framework.

C:\app\pulpfi [ln_create +5 ~5 -0 !]> artisan tinker
Psy Shell v0.8.1 (PHP 7.1.1-1+deb.sury.org~xenial+1 — cli) by Justin Hileman
>>> $faker = Faker\Factory::create('ja_JP')
=> Faker\Generator {#677}
>>> $faker->realText
PHP warning:  mb_substr() expects parameter 3 to be integer, string given in /opt/project/vendor/fzaninotto/faker/src/Faker/Provider/ja_JP/Text.php on line 623

```

**Comment by fzaninotto** [comment]
I know, the fix is in master, currently unreleased
