### ISSUE TITLE
Faker person pt_BR provider Using $this when not in object context

### ISSUE THREAD

**Issue by mihazs** [fzaninotto/Faker#1655]
Hello.
I'm trying to use the pt_br provider, and i'm getting the current error:
```
Fatal error: Uncaught Error: Using $this when not in object context in /app/vendor/fzaninotto/faker/src/Faker/Provider/pt_BR/Person.php:113

Stack trace:
#0 [internal function]: Faker\Provider\pt_BR\Person::cpf()
#1 /app/vendor/fzaninotto/faker/src/Faker/Generator.php(222): call_user_func_array(Array, Array)
#2 /app/vendor/fzaninotto/faker/src/Faker/Generator.php(279): Faker\Generator->format('cpf', Array)
#3 /app/models/vertex/Aluno.php(25): Faker\Generator->__call('cpf', Array)

```

I've expected just to generate the cpf.

**Comment by raphaeldealmeida** [comment]
Please send the code

**Comment by pimjansen** [comment]
@mihazs could you please show us some example code? There is no way for us to help like this

**Comment by mihazs** [comment]
I've already resolved, sorry for the late.
It's my bad use of imports. Thanks
