### ISSUE TITLE
 'Unknown formatter "suffix"' with en_US

### ISSUE THREAD

**Issue by Darkflib** [fzaninotto/Faker#973]
```
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Unknown formatter "suffix"' in /var/www/ice.yt/vendor/fzaninotto/faker/src/Faker/Generator.php:214
Stack trace:
#0 /var/www/ice.yt/vendor/fzaninotto/faker/src/Faker/Generator.php(196): Faker\Generator->getFormatter('suffix')
#1 /var/www/ice.yt/vendor/fzaninotto/faker/src/Faker/Generator.php(230): Faker\Generator->format('suffix')
#2 [internal function]: Faker\Generator->callFormatWithMatches(Array)
#3 /var/www/ice.yt/vendor/fzaninotto/faker/src/Faker/Generator.php(225): preg_replace_callback('/\\{\\{\\s?(\\w+)\\s...', Array, '{{firstNameMale...')
#4 /var/www/ice.yt/vendor/fzaninotto/faker/src/Faker/Provider/Person.php(57): Faker\Generator->parse('{{firstNameMale...')
#5 /var/www/ice.yt/gen-testuser.php(26): Faker\Provider\Person->name()
#6 {main}
  thrown in /var/www/ice.yt/vendor/fzaninotto/faker/src/Faker/Generator.php on line 214
```

Appears to be caused by:
```
$name=new Faker\Provider\en_US\Person($faker);
$user['name']['displayName']=$name->name();
```

This is using version "44f9a286a04b80c76a4e5fb7aad8bb539b920123"

If I have time I will try to debug it myself, best guess is that en_US doesn't include a suffix formatter ;)

**Comment by Newman101** [comment]
Hi. 

Looks like this was fixed on the latest version. I attempted to reproduce the code and it works normally.

**Comment by fzaninotto** [comment]
Yep, please use the master build until a new version is released.
